int _putchar(char x);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int s);
int _isalpha(int s);
int print_sign(int s);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int s);
void print_times_table(int s);
